const BOOKS = 'books/setBooks'
const LOADING_TOGGLE_ACTION = '[Loading action] toggle loading'
const BOOKS_ERROR = 'BOOKS_ERROR'
const FETCH_INITIAL_DATA_ERROR = 'FETCH_INITIAL_DATA_ERROR'
const FETCH_INITIAL_DATA_REQUEST = 'FETCH_INITIAL_DATA_REQUEST';
const FETCH_INITIAL_DATA_SUCCESS = 'FETCH_INITIAL_DATA_SUCCESS';
const CHANGE_CATEGORY = 'CHANGE_CATEGORY'
const BOOK_ID = 'BOOK_ID'
const ID_ERROR = 'ID_ERROR'
const COUNT_BOOK = 'COUNT_BOOK'
const LOAD__BOOKS_MORE = 'LOAD__BOOKS_MORE'
const CHANGE_SORT = 'CHANGE_SORT'

export {
    BOOKS, 
    LOADING_TOGGLE_ACTION, 
    BOOKS_ERROR, 
    FETCH_INITIAL_DATA_ERROR, 
    FETCH_INITIAL_DATA_REQUEST, 
    FETCH_INITIAL_DATA_SUCCESS,
    CHANGE_CATEGORY,
    BOOK_ID,
    ID_ERROR,
    COUNT_BOOK,
    LOAD__BOOKS_MORE,
    CHANGE_SORT
}